# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostIP', models.CharField(default=b'-', max_length=16)),
                ('USER', models.CharField(blank=True, max_length=16, null=True)),
                ('PID', models.CharField(blank=True, max_length=8, null=True)),
                ('CPU', models.CharField(blank=True, max_length=8, null=True)),
                ('MEM', models.CharField(blank=True, max_length=8, null=True)),
                ('START', models.CharField(blank=True, max_length=16, null=True)),
                ('TIME', models.CharField(blank=True, max_length=16, null=True)),
                ('COMMAND', models.CharField(blank=True, max_length=2048, null=True)),
                ('STAT', models.CharField(blank=True, max_length=8, null=True)),
                ('CollectTime', models.CharField(blank=True, default=b'1970-01-01 00:00:00', max_length=20, null=True)),
            ],
        ),
    ]
