---
- hosts: "{{ project_name }}"
  gather_facts: no
  vars:
    date_time: "{{ backup_time }}"
    # backup_path: /opt/backup/
  remote_user: tomcat

  tasks:

    - name: kill tomcat
      shell: ps aux|grep tomcat_{{ project_name }}|grep -v grep|awk '{print $2}'|xargs -i kill -9 {}
      ignore_errors: True

    - name: check if project directory exists
      stat: path=/opt/tomcat_{{ project_name }}/
      register: project_stat

    - name: create /opt/backup/
      file: dest=/opt/backup mode=755 state=directory

#    - name: use archive to backup 
#      archive: dest=/opt/backup/{{ project_name }}_{{ date_time }}.tgz path=/opt/tomcat_{{ project_name }}
#      tags:
#        - use_archive_to_backup
#      when: project_stat.stat.exists
#      ignore_errors: True

    - name: delete old project
      file: path=/opt/tomcat_{{ project_name }} state=absent
      tags:
        - delete_old_project
      when: project_stat.stat.exists
      ignore_errors: True

    - name: sync file
      unarchive: src={{ project_pack }} dest=/opt/
      tags:
        - sync_file
      register: sync_result

    - name: Set JAVA_HOME 
      lineinfile: dest=/opt/tomcat_{{ project_name }}/bin/setenv.sh line='export JAVA_HOME=/usr/java/jdk1.7.0_55' create=yes state=present mode=0555

    - name: set all file in bin attributes 0555
      file: path=/opt/tomcat_{{ project_name }}/bin  recurse=yes state=directory mode="u+x"
    
    # 修改项目端口 

    - name: replace port
      replace:
        dest=/opt/tomcat_{{ project_name }}/conf/server.xml
        backup=yes
        regexp={{ item.reg }}
        replace={{ item.rep }}
      with_items:
        - {reg: '(Server port=)"\d+"( shutdown="SHUTDOWN")', rep: '\1"{{ project_port | int - 1 }}"\2'}
        - {reg: '(Connector port=)"\d+"( protocol="HTTP/1.1")', rep: '\1"{{ project_port }}"\2'}
        - {reg: '(redirectPort=)"\d+"', rep: '\1"{{ project_port | int + 1 }}"'}
        - {reg: '(Connector port=)"\d+"( protocol="AJP/1.3")', rep: '\1"{{ project_port | int + 2 }}"\2'}

    # 移动日志文件夹到NFS目录并软链接回项目文件夹内

    - name: create project log directory of nfs
      file: path=/tomcat_logs/tomcat_{{ project_name }}/logs state=directory

#    - name: check if project log directory exists
#      stat: path=/opt/tomcat_{{ project_name }}/logs/
#      register: logs_stat
#
#    - name: copy logs directory to nfs directory
#      command: cp -rf /opt/tomcat_{{ project_name }}/logs/ /tomcat_logs/tomcat_{{ project_name }}/
#      when: logs_stat.stat.exists
#      ignore_errors: True

    - name: delete logs directory
      file: path=/opt/tomcat_{{ project_name }}/logs/ state=absent
#      when: logs_stat.stat.exists

    - name: link nfs log directory back to project logs directory
      file: src=/tomcat_logs/tomcat_{{ project_name }}/logs/ dest=/opt/tomcat_{{ project_name }}/logs state=link 
    
    # 启动tomcat

    - name: start tomcat
      shell: chdir=/opt/tomcat_{{ project_name }}/bin/ nohup ./startup.sh &
      tags:
        - start_tomcat
      when: sync_result|success
      #register: restart_result
      #ignore_errors: True
