# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=16)),
                ('project_name', models.CharField(max_length=200)),
                ('dest_server', models.CharField(max_length=200)),
                ('log_date', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('user', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('ftp_path', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
    ]
