# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actionuser', models.CharField(max_length=16)),
                ('Actiontime', models.CharField(max_length=32)),
                ('Actiontype', models.CharField(max_length=16)),
                ('Actionmodule', models.CharField(max_length=16)),
                ('Actioninfo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loginuser', models.CharField(default=b'-', max_length=16)),
                ('Logintime', models.CharField(blank=True, default=b'-', max_length=32, null=True)),
                ('Logouttime', models.CharField(blank=True, default=b'-', max_length=32, null=True)),
                ('Logaction', models.CharField(default=b'-', max_length=32)),
                ('LogIP', models.CharField(default=b'0.0.0.0', max_length=16)),
            ],
        ),
    ]
