# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('project_server', models.CharField(max_length=300)),
                ('project_msg', models.CharField(max_length=999, null=True)),
                ('project_port', models.IntegerField()),
                ('create_time', models.CharField(default='0000-00-00 00:00:00', max_length=32)),
                ('create_user', models.CharField(default='-', max_length=16)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_user', models.CharField(blank=True, max_length=32, null=True)),
                ('project_status', models.CharField(default='1', max_length=4)),
            ],
        ),
    ]
