# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-13 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=60)),
                ('server_ip', models.CharField(max_length=16)),
                ('ssh_port', models.CharField(max_length=8)),
                ('root_passwd', models.CharField(max_length=16)),
                ('server_remark', models.CharField(max_length=60)),
                ('create_time', models.CharField(default='0000-00-00 00:00:00', max_length=32)),
                ('create_user', models.CharField(default='-', max_length=16)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_user', models.CharField(blank=True, max_length=32, null=True)),
                ('server_status', models.CharField(default='1', max_length=4)),
            ],
        ),
    ]
