# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=16)),
                ('project_name', models.CharField(max_length=200)),
                ('dest_server', models.CharField(max_length=200)),
                ('deployment_pack', models.CharField(max_length=100, null=True)),
                ('log_date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PublishInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_state', models.CharField(default='\u5ba1\u6838\u4e2d', max_length=10)),
                ('publish_module', models.CharField(max_length=30)),
                ('publish_filename', models.CharField(max_length=30)),
                ('publish_user', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('user', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('ftp_path', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
                ('have_publish', models.CharField(default='1', max_length=4)),
                ('have_review', models.CharField(default='1', max_length=4)),
                ('have_test', models.CharField(default='1', max_length=4)),
            ],
        ),
    ]
